### ISSUE TITLE
List in TeSS

### ISSUE THREAD

**Issue by dannon** [bgruening/training-material#151] opened 2016-10-26 15:35 UTC
I'm going to look into maybe automatically listing these at https://tess.elixir-uk.org/ for more discoverability.

**Comment by bgruening** [comment] 2016-10-26 15:43
duplicate of https://github.com/bgruening/training-material/issues/46

Thanks @dannon this is a great idea and we should do this asap.

**Closed by bgruening** 2016-10-26 15:43 UTC

**Comment by dannon** [comment] 2016-10-26 15:44
That's what I get for making issues during talks, without scanning all the open ones first!  Yeah, it looks very doable.  I'll follow #46.
